import CodeBlock from "../../../components/ui/CodeBlock";

function BuildingPersonalWebsiteEn({ imageBase, githubPagesDocumentUrl }) {
  return <>
    <p className="article-meta">July 23, 2026 / Computer / Website</p>
    <h1>A Record of Building My Personal Website with Codex</h1>
    <p className="article-subtitle">Deploying a personal website with GitHub Pages, Cloudflare, and Codex</p>
    <p>Some time ago, I mentioned in another post that I bought a domain and found a server for writing a personal homepage. Over the last two days I refined it and added more content, so I am opening this post to record and share my deployment process. I barely touched the code throughout the process and made Codex do all the hard work. I mixed GPT-5.5 and GPT-5.6-sol, and every bit of usage was covered by my Plus plan.</p>
    <p>The idea was to host the static site on GitHub Pages and manage the domain through Cloudflare, using subdomains for different purposes. I created a dedicated academic DNS record to host my CV separately from the main site containing fanfiction and blog posts.</p>
    <h2>Step 1: Connect GitHub</h2><p>First, I connected Codex to GitHub. This can be configured directly under plugins and apps, or you can ask Codex to initiate the setup. Either way, I connected GitHub after completing 2FA verification.</p>
    <h2>Step 2: Create the site locally</h2><p>Second, I used local Git to create a repository, which Codex could complete by itself. I briefly described the layout I wanted and uploaded an avatar and background image, which I had actually taken from the Bilibili frontend. I looked at several other personal sites for reference and settled on my own layout.</p><p>Codex was smart enough to adjust the CSS for different screen sizes. I had not thought of that at first, and it also handled the centering very well.</p>
    <h2>Step 3: Define the structure</h2><p>Third, I manually gave it the site structure I wanted, roughly:</p><CodeBlock>{`Home
├─ Research
├─ Blogs
├─ Links
└─ Contact me`}</CodeBlock><p>Codex understood the idea precisely. Unfortunately, for some reason it initially wrote every child page in the form <code>/#/blogs</code>, so I asked it to change that.</p>
    <h2>Step 4: Add child pages</h2><p>Fourth, I added child pages. I required code to be displayed in copyable code blocks. I collected old posts scattered across several sites, fed them to GPT together with the original pages as layout references, and obtained very good article pages.</p><figure><img className="article-photo article-photo-wide" src={`${imageBase}copyable-code-block.png`} alt="A copyable code block in a personal-site article" /><figcaption>A code block with a one-click Copy button.</figcaption></figure>
    <h2>Step 5: Complete directories and links</h2><p>The fifth step was adding article directories, hyperlinks under Links, and similar details. Once I gave it the requirements, the results looked good. Up to this point, nothing had to be pushed to the cloud.</p>
    <h2>Step 6: Deploy with GitHub Actions</h2><p>The sixth step was creating the GitHub project and pushing it. Codex can create an Action to build and deploy the site. Once you provide the domain you want to bind, the generated deployment can target that domain.</p>
    <h2>Step 7: Bind the domain</h2><p>GitHub Pages provides four IPv4 addresses and four IPv6 addresses. The current ranges can be found in GitHub's <a href={githubPagesDocumentUrl} target="_blank" rel="noreferrer">documentation</a>.</p><figure><img className="article-photo article-photo-wide" src={`${imageBase}github-pages-ip-addresses.png`} alt="IPv4 and IPv6 addresses in the GitHub Pages documentation" /><figcaption>A and AAAA record addresses listed by GitHub Pages.</figcaption></figure><p>I added the corresponding records at the DNS provider. I used A and AAAA records, including IPv6, rather than an ALIAS record, and enabled the Cloudflare proxy for additional protection.</p><figure><img className="article-photo article-photo-wide" src={`${imageBase}cloudflare-dns-records.png`} alt="GitHub Pages DNS records configured in Cloudflare" /><figcaption>DNS records and proxy status in Cloudflare.</figcaption></figure><p>After that, the site was ready to use.</p>
    <h2>The academic subdomain</h2><p>For the academic subdomain, I uploaded my CV to Codex, described the style I wanted, and asked it to deploy directly. The first result was already acceptable. Later, I also created a social sharing image and favicon to make the site look more polished.</p><p>I used a subdomain because separating my academic CV from daily blogs, fanfiction, and ACGN content seemed more professional. If I did not write a blog, I might simply have hosted the CV on a child page.</p><figure><img className="article-photo article-photo-wide" src={`${imageBase}academic-cv-codex-chat.png`} alt="A Codex conversation about deploying the academic CV site" /><figcaption>Deploying the academic CV as a separate subdomain project.</figcaption></figure>
    <h2>Contact form and anti-spam measures</h2><p>Finally, as a personal preference, I asked Codex to add a Contact me function using FormSubmit. Once I owned a domain, Cloudflare could host an email-forwarding address, so I used that forwarding address to improve privacy. I also asked Codex to enable several anti-spam measures and added a robots.txt file to specify crawler rules, although the public GitHub repository can still be downloaded directly.</p><p>After another push and confirming the FormSubmit activation email, the site was finished.</p>
  </>;
}
export default BuildingPersonalWebsiteEn;
