function Comsol64GpuTestEn({ imageBase }) {
  return <>
    <p className="article-meta">July 23, 2026 / Modelling / COMSOL</p>
    <h1>A Simple Test of GPU Acceleration in COMSOL 6.4</h1>
    <p className="article-subtitle">A personal test of COMSOL 6.4, cuDSS, and a consumer GPU</p>
    <aside className="article-note"><p><strong>Second edit:</strong> A teacher from IC in my WeChat Moments shared that COMSOL can fully utilize the GPU on their system. I am still exploring the reason for the difference. Based on our configurations, my preliminary guess is that the CPU and GPU work serially in this calculation: the CPU assembles the global stiffness matrix before the GPU solves the sparse system. My CPU therefore unfortunately became the bottleneck.</p><p>This also means that in this new version, we can no longer simply maximize CPU and memory as before. We need to consider model complexity, the balance between CPU and GPU efficiency, and the relationship between VRAM and system memory. It also shows that consumer GPUs still have considerable potential to be explored.</p></aside>
    <h2>Background</h2><p>COMSOL recently released version 6.4, and I was fortunate enough to receive a trial code. I therefore decided to run several examples on my personal computer and observe the resource usage. I often see people configuring computers for COMSOL, and this version contains many computational improvements, so I am sharing a simple personal test for reference.</p>
    <h2>Main improvements in COMSOL 6.4</h2><p>First, let us review the main changes:</p><ul><li>The cuDSS solver was added.</li><li>Explicit dynamics and the Granular Flow Module were added.</li><li>The chatbot supports OpenAI-compatible models such as Qwen and DeepSeek.</li><li>CUDA and multi-GPU computation are supported.</li></ul>
    <p>COMSOL published the following multi-GPU result for an office acoustics model with frequency-dependent impedance data, a spatial Gaussian pulse centered at 500 Hz, 20 periods, and 50 million degrees of freedom:</p><ul><li>1 GPU (NVIDIA RTX 6000 Ada): 29 minutes, 92.3 ms/ts.</li><li>2 GPUs (NVIDIA RTX 6000 Ada): 18 minutes, 53.0 ms/ts.</li><li>CPU only (Xeon w5-2445X, 12 cores): 14 hours.</li></ul><p>From this dataset, it is clear that COMSOL is no longer software that uses only CPU resources. A powerful GPU can also provide substantial help.</p>
    <h2>When should GPU resources be considered?</h2><p>Let us return to the finite-element solution process.</p><p>After meshing, the solver first obtains the stiffness matrix of each element and assembles the global stiffness matrix. At present, the cuDSS used by COMSOL can only accelerate the computation involving the global stiffness matrix. Therefore, for many implicit transient models, the GPU benefit may be limited, while explicit models may obtain a larger improvement in solution efficiency.</p><p>COMSOL engineers have also pointed out that sufficient VRAM is needed. In tests by @Entropy.S.I, COMSOL's system-memory demand was enormous. Much intermediate data and many matrices are processed in memory rather than written to disk, and are released directly afterward.</p><p>The same principle applies to GPU computation. COMSOL offers a hybrid mode that can use system memory when necessary, but VRAM is clearly faster than system memory used through the hybrid path.</p>
    <h2>Test on my computer</h2><p>Without other optimization, I ran an explicit-dynamics battery-impact simulation in COMSOL 6.4 for Windows on my RTX 3070 Ti Laptop GPU. I selected cuDSS, with the remaining settings shown below.</p>
    <figure><img className="article-photo article-photo-wide" src={`${imageBase}cudss-solver-settings.png`} alt="cuDSS and hybrid-computing settings in COMSOL 6.4" /><figcaption>cuDSS, single precision, and hybrid-computing settings.</figcaption></figure>
    <p>Throughout the calculation, average GPU utilization stayed below 13%. Dedicated VRAM usage was about 1 GB, still some distance from the maximum I configured. Because this is a consumer GPU with limited double-precision capability, I selected single precision.</p>
    <figure><img className="article-photo" src={`${imageBase}gpu-usage-test-1.png`} alt="GPU usage during the first COMSOL 6.4 test" /><figcaption>GPU and dedicated-memory usage in the first test.</figcaption></figure>
    <figure><img className="article-photo" src={`${imageBase}gpu-usage-test-2.png`} alt="Another interval of GPU usage in the explicit-dynamics test" /><figcaption>Another recorded interval during the same test.</figcaption></figure>
    <p>In another example, average utilization was also below 13%, and dedicated memory usage was only about 1 GB.</p>
    <figure><img className="article-photo" src={`${imageBase}gpu-usage-test-3.png`} alt="GPU usage in another COMSOL 6.4 example" /><figcaption>GPU and VRAM usage in another example.</figcaption></figure>
    <h2>Conclusion</h2><p>Overall, although COMSOL now supports cuDSS, its use of system GPU resources in my tests was still conservative. One task did not fully occupy the GPU, which may also be related to how these two models were discretized.</p><p>At this stage, users without special requirements do not need to rush to upgrade their GPU solely for accelerated solving. In my tests, system memory remained the priority resource.</p>
  </>;
}
export default Comsol64GpuTestEn;
