function UniversalStudiosEn({ imageBase, sourceUrl }) {
  return <>
    <p className="article-meta">July 27, 2022 / Life / Travel</p>
    <h1>Our Sparkling Universal Studios Guide</h1><p className="article-subtitle">Universal Studios Beijing</p>
    <h2>1. Tickets, hotels, and luggage before the trip</h2><p>Based on our advance research, there is no need to book The Universal Studios Grand Hotel or NUO Resort Hotel. They are expensive, and the included privileges did not seem very useful to us. A nearby hotel is completely fine. You can compare the options using the spreadsheet we prepared.</p><figure><img className="article-photo article-photo-wide" src={`${imageBase}hotel-comparison.png`} alt="Comparison of prices and transport for hotels near Universal Studios Beijing" /><figcaption>Chart 1: Prices were current when we checked them.</figcaption></figure>
    <p>We did not recommend buying standard tickets or 1.5-day tickets directly from the official site. University students could receive discounts through Dianping and Meituan, bringing a one-day ticket to RMB 540 and two days to RMB 1,080. The money saved could be used for Express Passes.</p><p>Individual Express Passes could be purchased in the mini program. Do not buy the RMB 700 pass: each attraction can only be used once, and it includes several attractions that normally have short queues anyway. We recommended individual passes for Harry Potter and the Forbidden Journey, Transformers: Battle for the AllSpark, and Jurassic World Adventure. Buying them on the morning of the visit was enough for us, but they could sell out, so be quick.</p><p>Buy wizard robes and ties on Taobao before leaving because they are much cheaper than inside the park. The wand chooses the wizard, though, so we bought ours from Ollivanders. Also bring a raincoat for the WaterWorld show. Do not take large luggage into the park; leave it with the hotel after checkout, since most hotels provide luggage storage.</p><p><strong>How to buy an individual Express Pass:</strong></p>
    <div className="article-image-grid" aria-label="Steps for buying an individual Express Pass"><figure><img className="article-photo article-photo-phone" src={`${imageBase}express-pass-entry.png`} alt="Express Pass entry in the resort mini program" /><figcaption>Swipe right on the home page to find Express Pass.</figcaption></figure><figure><img className="article-photo article-photo-phone" src={`${imageBase}single-express-pass.png`} alt="Individual Express Pass option" /><figcaption>Select the individual Express Pass.</figcaption></figure><figure><img className="article-photo article-photo-phone" src={`${imageBase}single-pass-options.png`} alt="Attraction selection for an individual Express Pass" /><figcaption>Select the attraction you want.</figcaption></figure></div>
    <h2>2. Entering the park, attractions, and shows</h2><p>The park opened at 10 a.m., but we recommended reaching security at the CityWalk entrance at about 9 a.m.; security opened at 8. Then move quickly to the main entrance queue and reserve entry through the mini program. Arriving too late might prevent you from entering before 10.</p><p>Without individual Express Passes, go directly to Forbidden Journey, Battle for the AllSpark, and Jurassic World Adventure, because their queues are shortest in the morning. Queue times might drop to about 60 minutes around 4 or 5 p.m. and 40 minutes after 6 p.m. However, an attraction could close if you had not entered by 7.</p><p>With Express Passes, start with less crowded attractions such as Minion Mayhem or Flight of the Hippogriff. At noon, when popular rides such as Forbidden Journey reach 100-minute waits, use the passes for those attractions. Save Lights, Camera, Action! for the end because its queue stayed below 20 minutes during our visit. Decepticoaster could also be quieter around 4 or 5 p.m.; one possible plan was to queue for Untrainable at 3:30, leave around 4:30, and then visit Decepticoaster and Battle for the AllSpark.</p><p>We strongly recommended the Untrainable and WaterWorld shows. There was no need to queue extremely early for WaterWorld if you had a raincoat, because you could go straight to the front row. We entered only three minutes before the show and reached the front without queueing. For Untrainable, arrive half an hour early in case seats run out. The Universal on Parade event took over the main road at about 6 p.m.; if you did not want to watch, plan your route beforehand or stay within one themed area.</p><p>Keep checking the mini program because its wait times were relatively accurate. You did not need to store your phone for Forbidden Journey, so you could take photos inside the castle. For Decepticoaster, everything except glasses had to go in a locker, or staff would send you back.</p>
    <h2>3. Food</h2><p>We ate at Three Broomsticks and Hammond's. Three Broomsticks was relatively inexpensive and generous, but required queueing. Butterbeer could be ordered with the meal, but adding food later meant queueing again. Hammond's served smaller and more expensive portions, but felt very upscale and offered a text-message waiting list. The food at both restaurants was delicious.</p><p>Butterbeer was also available at Hog's Head with almost no queue. Minion ice cream could be bought in the shop inside Super Swirly, and Minion popcorn was available on Hollywood Boulevard. The carts had very long queues, so we did not recommend them.</p>
    <h2>4. Photos</h2><p>For photographs, go in the morning or shortly before closing, when the streets are less crowded. Hollywood, The Wizarding World of Harry Potter, and Minion Land were especially suitable, with beautiful outdoor scenery. Kung Fu Panda Land also had good sets in theory, but the lighting was dark. Experienced photographers may still want to try it. The indoor area of Isla Nublar near Jurassic Flyers was also good for photos.</p>
    <aside className="article-note"><p>One final note: all of this comes from our own experience. Everyone will feel differently, and our comments differ from some guides on Xiaohongshu. For example, some people find Flight of the Hippogriff boring, but we still screamed loudly. Do not feel restricted by a guide; follow your own preferences and have fun. I hope every friend has a unique and perfect Universal Studios trip!</p><p>That is everything I can think of. Huihui, come and add more! bεOvO3d</p><p>Yangyang should debut as a professional reviewer immediately! Huihui has finished adding her part too! :3</p></aside>
    <p className="article-source">Original: <a href={sourceUrl} target="_blank" rel="noreferrer">Raining Sunshine / Blogger</a></p>
  </>;
}
export default UniversalStudiosEn;
