export const routes = {
  home: "home",
  blog: "blog",
  modelling: "modelling",
  comsol64Test: "blogs/modelling/COMSOL64-test",
  neuralNetworkIntroduction: "blogs/modelling/neural-network-introduction",
  flaskGeometry: "blogs/modelling/flask-geometry-without-parametric-curves",
  computer: "computer",
  life: "life",
  universalStudios: "universal-studios-beijing",
  frpRdp: "frp-rdp",
  buildingPersonalWebsite: "blogs/computer/building-personal-website",
  research: "research",
  links: "links",
  contact: "contact",
};
